name: ci

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Node 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm install
            - run: npm run lint
